language: groovy
env:
  global:
    secure: c1AOS/lmLlvSxXt1Y7BxQztLcYs5AV5XQWg313jo3ZyEH9OklhRl3tlFpDs+rtrXzIiairAyXQdjDW7MiO3Gw1KCwFIQ9cHQKEUobqqPVPYzdKdc3l/8zX6bPkv57CbkLsWjYV6aUeHkf8uoetUAUenLTcVqYh0n4M7+9tnNN8rmuUdC18vdlC9HMIYK5J+VeuvjE/Tm7MrzC+SFmphRcvENOAvJ4riIIO0mgFu3Mk3gGqNFvgFc00ZuVlf6jVzKm46A5v/kvGhJyUz497kNjFsZVGnVES/1Hcn+ms4q/64ji9Gd3/Byoegu6v2FR3eHLpA9Q1PWXv0Ob7Pq05v2EPjNqwA/P2d07r+TiO9UvX2SKVhm3gdUpg1DdNjT1uxl89x6xuZeOLXWXJaCpNxkb3VEu5z2U3gE7qHG3Xk/TWHG9FQIFCJRRAuJXjNT5TtYfzLiYtZnD3RoMqUCYWdNSQmw26hiJ/WDPdX1hjDrCJW3vunLqvs6mkloAkzccmWteouQyleAKGVepBkSl4K3Z0I9vrFXbXegV5Ee6eCsHJizuX2hEhUSNA2fIfTTGR57+ohtRMZLQALb+fO7OVFrZab4xrXn0APA7aWW1mVBbncSZQud1YLbn1PbyngEL/1SCnyTwuXR7MKK8XNv23iO0oOV4wzZh9PokzP6sxzzk+w=

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: qNoL5rbZxNWM4mCCqZ+7JQb9BH0JbCuIOBbyTtIj730VG9TzI3nBh9sDG1BlBWIjx9avrCRYdNxSS5vIjUliLdIBx3VzQySvzcnU8P2X0kjl7FmFrvu7zxfB66JkhFQopGOptzI/4Z49JM3n0oFdebiaMZl19jVjaHcQTwtK20I5lYdZejNrv9/gxrxcghMTZ3pWSufnh9IwSIVktfiPw0VWH56cfqa9vNNpJsUwXXMHJEf8FGtQUUvGInkPP2fJq9AbRJw7eBSQ3MgXAOzRjhETglLPfWHrpT4WKrmd1+v6/M1NfP/iLqEicAHPfdCVNUdponKAziDT7+lcvkkCK4/UuXtGGFRMVdFs9ntXeVilYGPDPoRKNOpSjgozivtPI8l6HFyi+RTPlJxSHsi9spi2DC8i88BNIONayk5SLC0DCLq/oRXTe202eZgeePJi+N3TFm2tBG/C83mnUeNU/IQljCM3gmexH7U62ze2aDOZRf2pJnLV2HS2eDv1TkKN43AKjkHE9fKyC47XPEbc793P3r8slYDLz54E3bFVSC5ISshxL04xMMNVwZi3/hIm77Ju8SVu+r05BM11CcHbLPtmmsoFFeLFKuupa7HefkYbWA6FC1D/m0rfbgOL7sFUZXDZHBUe8nbrisN++RsBZUUbl/aKjLx7Y3MTTdOdWv4=
